/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/rewards': typeof RewardsRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/rewards': typeof RewardsRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/rewards': typeof RewardsRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/parents' | '/play' | '/rewards' | '/worlds' | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parents' | '/play' | '/rewards' | '/worlds' | '/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/parents'
    | '/play'
    | '/rewards'
    | '/worlds'
    | '/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentsRoute: typeof ParentsRoute
  PlayRoute: typeof PlayRoute
  RewardsRoute: typeof RewardsRoute
  WorldsRoute: typeof WorldsRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentsRoute: ParentsRoute,
  PlayRoute: PlayRoute,
  RewardsRoute: RewardsRoute,
  WorldsRoute: WorldsRoute,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
